version: "3.5"
services:
    mosquitto:
        image: eclipse-mosquitto
        hostname: mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - mqtt-conf:/mosquitto/mosquitto.conf
        deploy:
            restart_policy:
                condition: on-failure

    subscriber:
        image: eclipse-mosquitto
        depends_on: 
            - mosquitto
        command: ["mosquitto_sub", "-h", "mosquitto", "-t", "test"]
            
    temperature:
        image: eclipse-mosquitto
        depends_on: 
            - mosquitto
            - subscriber
        command: ["mosquitto_pub", "-h", "mosquitto", "-t", "test", "-m", "33.5°F"]
        deploy:
            restart_policy:
                delay: 30s
                window: 15s
    
    wind:
        image: eclipse-mosquitto
        depends_on: 
            - mosquitto
            - subscriber
        command: ["mosquitto_pub", "-h", "mosquitto", "-t", "test", "-m", "SSW @ 3 MPH"]
        deploy:
            restart_policy:
                delay: 10s
                window: 15s

    last_updated:
        image: eclipse-mosquitto
        depends_on: 
            - mosquitto
            - subscriber
        command: ["mosquitto_pub", "-h", "mosquitto", "-t", "test", "-m", "13:35EST 02/15"]
        deploy:
            restart_policy:
                delay: 60s
                window: 15s

volumes:
    mqtt-conf:
